export const jobs = [
  {
    id: 1,
    jobName: "Software Engineer",
    role: "Developer",
    category: "IT",
    location: "San Francisco",
    salary: "$80,000",
    timeShift: "Full-Time",
    experience: "3+ years",
    type: "Onsite",
    jobDescription: "Develop and maintain software applications, participate in the full software development lifecycle.",
    otherDetails: [
      { industry: "Information Technology", type: "Software Development" },
    ],
  },
  {
    id: 2,
    jobName: "Marketing Specialist",
    role: "Specialist",
    category: "Marketing",
    location: "New York",
    salary: "$60,000",
    timeShift: "Part-Time",
    experience: "2+ years",
    type: "Remote",
    jobDescription: "Create and implement marketing strategies, analyze market trends, and execute advertising campaigns.",
    otherDetails: [
      { industry: "Marketing", type: "Advertising" },
    ],
  },
  {
    id: 3,
    jobName: "Data Scientist",
    role: "Scientist",
    category: "Data Science",
    location: "Austin",
    salary: "$90,000",
    timeShift: "Full-Time",
    experience: "4+ years",
    type: "Both",
    jobDescription: "Utilize statistical methods to analyze data, develop machine learning models, and provide insights.",
    otherDetails: [
      { industry: "Information Technology", type: "Data Analytics" },
    ],
  },
  {
    id: 4,
    jobName: "Network Administrator",
    role: "Administrator",
    category: "IT",
    location: "Seattle",
    salary: "$75,000",
    timeShift: "Full-Time",
    experience: "5+ years",
    type: "Onsite",
    jobDescription: "Manage and maintain computer networks, troubleshoot connectivity issues, and implement security measures.",
    otherDetails: [
      { industry: "Information Technology", type: "Network Administration" },
    ],
  },
  {
    id: 5,
    jobName: "Graphic Designer",
    role: "Designer",
    category: "Design",
    location: "Los Angeles",
    salary: "$55,000",
    timeShift: "Full-Time",
    experience: "3+ years",
    type: "Onsite",
    jobDescription: "Create visual concepts and designs for various projects, collaborate with teams to produce high-quality graphics.",
    otherDetails: [
      { industry: "Design", type: "Graphic Design" },
    ],
  },
  {
    id: 6,
    jobName: "Financial Analyst",
    role: "Analyst",
    category: "Finance",
    location: "Chicago",
    salary: "$70,000",
    timeShift: "Full-Time",
    experience: "4+ years",
    type: "Onsite",
    jobDescription: "Analyze financial data, prepare reports, and provide insights to support decision-making processes.",
    otherDetails: [
      { industry: "Finance", type: "Financial Analysis" },
    ],
  },
  {
    id: 7,
    jobName: "Customer Support Representative",
    role: "Representative",
    category: "Customer Service",
    location: "Dallas",
    salary: "$45,000",
    timeShift: "Part-Time",
    experience: "1+ year",
    type: "Onsite",
    jobDescription: "Assist customers with inquiries, resolve issues, and provide excellent customer service.",
    otherDetails: [
      { industry: "Customer Service", type: "Support" },
    ],
  },
  {
    id: 8,
    jobName: "HR Specialist",
    role: "Specialist",
    category: "Human Resources",
    location: "Denver",
    salary: "$65,000",
    timeShift: "Full-Time",
    experience: "3+ years",
    type: "Onsite",
    jobDescription: "Handle various HR functions, including recruitment, employee relations, and benefits administration.",
    otherDetails: [
      { industry: "Human Resources", type: "HR Generalist" },
    ],
  },
  {
    id: 9,
    jobName: "Civil Engineer",
    role: "Engineer",
    category: "Engineering",
    location: "Houston",
    salary: "$85,000",
    timeShift: "Full-Time",
    experience: "5+ years",
    type: "Onsite",
    jobDescription: "Design and oversee construction projects, ensure compliance with regulations, and manage project budgets.",
    otherDetails: [
      { industry: "Engineering", type: "Civil Engineering" },
    ],
  },
  {
    id: 10,
    jobName: "Healthcare Administrator",
    role: "Administrator",
    category: "Healthcare",
    location: "Miami",
    salary: "$75,000",
    timeShift: "Full-Time",
    experience: "4+ years",
    type: "Onsite",
    jobDescription: "Manage healthcare facilities, coordinate medical services, and oversee administrative functions.",
    otherDetails: [
      { industry: "Healthcare", type: "Healthcare Administration" },
    ],
  },
  {
    id: 11,
    jobName: "Sales Representative",
    role: "Representative",
    category: "Sales",
    location: "Atlanta",
    salary: "$55,000",
    timeShift: "Full-Time",
    experience: "2+ years",
    type: "Remote",
    jobDescription: "Promote and sell products or services, build and maintain client relationships, and achieve sales targets.",
    otherDetails: [
      { industry: "Sales", type: "Sales Representative" },
    ],
  },
];
